const playersMockData = [
  {
    player_name: "Lohit Valavala",
    role: "All Rounder",
    team_name: "Hyderabad Titans",
    batting_avg: 20.46,
    batting_sr: 128.19,
    batting_highest: 62,
    matches: 57,
    batting_innings: 41,
    bowling_innings: 38,
    overs_bowled: 120.2,
    wickets: 63,
    economy: 6.75,
    bowling_avg: 18.2,
    bowling_sr: 19.5,
    five_wicket_hauls: 2,
    ten_wicket_hauls: 0
  },
  {
    player_name: "Anil Kumar",
    role: "Bowler",
    team_name: "Chennai Warriors",
    batting_avg: 12.5,
    batting_sr: 98.3,
    batting_highest: 34,
    matches: 45,
    batting_innings: 20,
    bowling_innings: 44,
    overs_bowled: 150.0,
    wickets: 72,
    economy: 5.9,
    bowling_avg: 15.7,
    bowling_sr: 17.2,
    five_wicket_hauls: 3,
    ten_wicket_hauls: 1
  },
  {
    player_name: "Suresh Reddy",
    role: "Batsman",
    team_name: "Mumbai Kings",
    batting_avg: 32.1,
    batting_sr: 135.7,
    batting_highest: 88,
    matches: 60,
    batting_innings: 58,
    bowling_innings: 2,
    overs_bowled: 3.0,
    wickets: 0,
    economy: 8.0,
    bowling_avg: 0,
    bowling_sr: 0,
    five_wicket_hauls: 0,
    ten_wicket_hauls: 0
  },
  {
    player_name: "Vikram Singh",
    role: "All Rounder",
    team_name: "Delhi Daredevils",
    batting_avg: 25.8,
    batting_sr: 120.4,
    batting_highest: 54,
    matches: 50,
    batting_innings: 40,
    bowling_innings: 35,
    overs_bowled: 100.0,
    wickets: 48,
    economy: 7.2,
    bowling_avg: 21.3,
    bowling_sr: 22.5,
    five_wicket_hauls: 1,
    ten_wicket_hauls: 0
  }
];

export default playersMockData; 